apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-crowd-config
  namespace: smart-crowd

data:
  NODE_ENV: "development"

  GATEWAY_PORT: "3000"

  OAUTH_SERVER_URL: "http://oauth-service:3002"

  CROWD_SERVICE_URL: "http://crowd-service:8000"

  INCIDENT_SERVICE_URL: "http://incident-service:8001"

  ENV_SERVICE_URL: "http://environment-service:8002"

  PYTHON_ML_URL: "http://python-ml-service:5000"

  RATE_LIMIT_WINDOW_MS: "900000"

  RATE_LIMIT_MAX: "100"

  AUTH_RATE_LIMIT_WINDOW_MS: "3600000"

  AUTH_RATE_LIMIT_MAX: "500"