persistence true
persistence_location /mosquitto/data/

log_dest stdout
log_type error
log_type warning
log_type notice
log_type information

listener 1883
protocol mqtt

listener 9001
protocol websockets

allow_anonymous true

connection_messages true

autosave_interval 180

max_inflight_messages 100

max_queued_messages 1000