apiVersion: v1
kind: Secret
metadata:
  name: smartcity-secret
  namespace: smartcity
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQ=
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
  JWT_SECRET: c21hcnRjaXR5LWs4cy1zZWNyZXQta2V5
  RABBITMQ_PASS: YWRtaW4xMjM=