apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: smart-crowd
  labels:
    app: gateway

spec:
  replicas: 2

  selector:
    matchLabels:
      app: gateway

  template:
    metadata:
      labels:
        app: gateway

    spec:
      containers:
        - name: gateway

          image: smart-crowd-gateway:latest

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 3000

          envFrom:
            - configMapRef:
                name: smart-crowd-config

            - secretRef:
                name: smart-crowd-secret

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 3000

            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 3000

            initialDelaySeconds: 20
            periodSeconds: 15