global:
  scrape_interval: 15s

scrape_configs:

  - job_name: gateway

    metrics_path: /metrics

    static_configs:
      - targets:
          - express-gateway:3000

  - job_name: oauth

    static_configs:
      - targets:
          - oauth-server:3002

  - job_name: python-ml

    static_configs:
      - targets:
          - python-ml:5000